from pydantic import BaseModel, Field
from typing import List

class SiteProfile(BaseModel):
    """Basic fields about the target site."""
    name: str = Field(description="Name of the target site")
    theme: str = Field(description="Theme or primary topic of the site")
    stack_hints: List[str] = Field(description="Hints about the tech stack (e.g., React, Express, PHP)")
    important_paths: List[str] = Field(description="List of important URLs or paths observed")

class DecoyAssetDefinition(BaseModel):
    """Fields describing fake pages, endpoints, methods, and response types."""
    endpoint: str = Field(description="The URL path for the decoy asset (e.g., '/admin/login.php')")
    method: str = Field(description="The HTTP method required (e.g., 'GET', 'POST')")
    response_type: str = Field(description="Type of response expected (e.g., 'html_admin_panel', 'json_error', 'env_file')")
    description: str = Field(description="A brief description of what this decoy is and what it aims to achieve.")

class DecoyAssetList(BaseModel):
    """Wrapper model for returning a list of assets from the LLM cleanly."""
    assets: List[DecoyAssetDefinition] = Field(description="List of decoy assets generated by the AI.")

class ForensicSummary(BaseModel):
    """Fields for summarizing a session."""
    headline: str = Field(default="Session Summary", description="A short headline for the session summary")
    description: str = Field(default="No detailed description provided by AI.", description="A detailed narrative of the session")
    suspected_techniques: List[str] = Field(default_factory=list, description="List of suspected attack techniques")
    recommendations: List[str] = Field(default_factory=list, description="Suggested response or mitigation strategies")
